language: elixir
elixir:
- 1.6.4
otp_release:
- 20.3

install:
- bash script/travis-install

script:
- bash script/travis-script
- bash script/travis-script-unit
- bash script/travis-script-integration

after_success:
- bash script/travis-after-success
