#!/bin/bash
########################
# Purpose: install the necessary project dependencies and create working environment
# Author: Prasad Talasila
# Date: 10-April-2017
# Invocation: This script does not require any arguements. From the project top-level
#             directory, invoke as follows
#             $bash script/bootstrap
########################

set -e      # bail out on failure

sudo apt-get update
sudo apt-get -y install git

sudo su ubuntu
git clone https://github.com/asdf-vm/asdf.git /home/vagrant/.asdf --branch v0.3.0
cp script/.bashrc /home/vagrant/.bashrc
source /home/vagrant/.bashrc
echo "\n . /home/vagrant/.bashrc" >> ~/.bashrc

sudo apt-get install -y automake autoconf libreadline-dev libncurses-dev libssl-dev libyaml-dev \
  libxslt-dev libffi-dev libtool unixodbc-dev make zip

asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
asdf list-all erlang
asdf install erlang 19.0
asdf list erlang
asdf global erlang 19.0

asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
asdf list-all elixir
asdf install elixir 1.3.4
asdf list elixir
asdf global elixir 1.3.4
