#!/bin/bash
########################
# Purpose: update the project and reinstall
# Author: Prasad Talasila
# Date: 10-April-2017
# Invocation: This script does not require any arguements. From the project top-level
#             directory, invoke as follows
#             $bash script/update
########################

set -e

cd /home/ubuntu/ts

# uncomment next line if you want to pull from github before server release
#source script/update

mix release

#undemonstrated, but can do remote deployment
#mix edeliver build release
#mix edeliver deploy release
#mix edeliver start
