#!/bin/bash
########################
# Purpose: run all the tests
# Author: Prasad Talasila
# Date: 10-April-2017
# Invocation: This script does not require any arguements. From the project top-level
#             directory, invoke as follows
#             $bash script/test
########################

set -e

cd "$TS_HOME"

#rm -rf ./data/*
#cp ./unit_data/* ./data/


#MIX_ENV=unit mix test

rm -rf ./data/*
cp ./apps/transport_scheduler/test/data/* ./data/

chmod o+w ./data/* 

MIX_ENV=integration mix test
