#!/bin/bash
########################
# Purpose: To perform CI on travis-ci.org
# Author: Prasad Talasila
# Date: 10-April-2017
# Invocation: This script does not require any arguements. From the project top-level
#             directory, invoke as follows. ONLY INVOKE INSIDE TRAVIS-CI ENVIRONMENT.
#             $bash script/travis
########################

set -e

source "$HOME/.bashrc"

mix compile

# report test coverage to coveralls.io
# shellcheck disable=SC2037
MIX_ENV=test mix coveralls.travis --umbrella --exclude slow

# report test coverage to codecov
# shellcheck disable=SC2037
MIX_ENV=test mix do compile coveralls.json

# lint code using credo
# shellcheck disable=SC2037
MIX_ENV=test mix credo --strict

mix test --exclude slow
mix profile

MIX_ENV=test mix coveralls.json --umbrella --exclude slow

bash <(curl -s https://codecov.io/bash) -f cover/excoveralls.json