#!/bin/bash
########################
# Purpose: To perform CI on travis-ci.org
# Author: Prasad Talasila
# Date: 10-April-2017
# Invocation: This script does not require any arguements. From the project top-level
#             directory, invoke as follows. ONLY INVOKE INSIDE TRAVIS-CI ENVIRONMENT.
#             $bash script/travis
########################

set -e

echo "Hello World"

# export code coverage report to codecov
# bash <(curl -s https://codecov.io/bash) -f cover/excoveralls.json
