#!/bin/bash
########################
# Purpose: update the project and reinstall
# Author: Prasad Talasila
# Date: 10-April-2017
# Invocation: This script does not require any arguements. From the project top-level
#             directory, invoke as follows
#             $bash script/update
########################

set -e

cd /home/vagrant/ts
git pull origin $(git rev-parse --abbrev-ref HEAD)

source /home/vagrant/.bashrc
mix local.rebar --force
mix local.hex --force
mix deps.get

source script/test        #make sure all tests pass
