#!/bin/bash
########################
# Purpose: update the project and reinstall
# Author: Prasad Talasila
# Date: 10-April-2017
# Invocation: This script does not require any arguements. From the project top-level
#             directory, invoke as follows
#             $bash script/update
########################
CONFIG_FILE=./home.conf

if [ -f $CONFIG_FILE ];
then
  # shellcheck disable=SC1090
  . "$CONFIG_FILE"
fi 

set -e

cd $TS_HOME
git pull origin $(git rev-parse --abbrev-ref HEAD)

source script/setup	  #run setup on the updated code base
source script/test        #make sure all tests pass
